# tomcat config
server:
  port: 9000
  servlet:
    context-path: /admin/api

# spring application config
spring:
  application:
    name: couture-data-admin
  # security memory config
  security:
    user:
      name: haiji
      password: yanghaiji